image:
  file: .gitpod.Dockerfile
ports:
  - port: 6080
    onOpen: open-preview
  - port: 35900
    onOpen: ignore
  - port: 5900
    onOpen: ignore
tasks:
  - init: yarn && gp sync-done yarn
    command: yarn start
    name: Server
  - init: gp sync-await yarn && yarn test
    name: Testing
    openMode: split-right
